# Disable sending stats
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

source 'https://github.com/CocoaPods/Specs.git'

project 'MeetupRaffle.xcodeproj'

platform :ios, '10.0'

inhibit_all_warnings!
use_frameworks!

target 'MeetupRaffle' do
    pod 'ALDataRequestView/ReactiveCocoa'
    pod 'Moya/ReactiveCocoa'
    pod 'Moya-JASONMapper'
    pod 'RxSwift'
    pod 'Moya-JASONMapper/ReactiveCocoa'
    pod 'ALReactiveCocoaExtension'
    pod 'ReactiveCocoa', :git => 'https://github.com/ReactiveCocoa/ReactiveCocoa.git'
    pod 'Nuke'
end


# Build configurations
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
        end
    end
end
